// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdHWIYvMQdJEnovueqdhzpm3yYJXj1Izw',
    appId: '1:293288678694:web:42ab61f663e54c47035de7',
    messagingSenderId: '293288678694',
    projectId: 'dadimulyo-606ad',
    authDomain: 'dadimulyo-606ad.firebaseapp.com',
    storageBucket: 'dadimulyo-606ad.firebasestorage.app',
    measurementId: 'G-6REYVDP7C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB71duPyj87JBxZxCd-kz6id2DJCD0qxnQ',
    appId: '1:293288678694:android:1efc5c9195bdbf11035de7',
    messagingSenderId: '293288678694',
    projectId: 'dadimulyo-606ad',
    storageBucket: 'dadimulyo-606ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNsXI7F82Hjb00xil64Q70rEQSnuUlSFo',
    appId: '1:293288678694:ios:e781444dfa92350a035de7',
    messagingSenderId: '293288678694',
    projectId: 'dadimulyo-606ad',
    storageBucket: 'dadimulyo-606ad.firebasestorage.app',
    iosBundleId: 'com.dadimulyo.dadiMulyoMobile',
  );
}
